version: '3.1'

services:
  redis:
    image: "redis:latest"
    restart: always
    container_name: redis
    ports: 
      - "6379:6379"

  rabbit:
    image: "rabbitmq:3-management"
    restart: always
    container_name: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbithole"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"

  xizhi:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - "redis"
      - "rabbit"
    container_name: xizhi
    environment:
      - MQ_HOST=rabbit
      - MQ_PORT=5672
      - MQ_USER=rabbitmq
      - MQ_PASSWORD=rabbithole
      - QUEUE=credstoreIn
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CH=result
      - LOG_LEVEL=INFO
